<a href="https://colab.research.google.com/github/Ekiiio/week5/blob/main/Numpy_Indexing2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [6]:
nums = np.arange(1,11)*100
#生成索引 idx idx 是一个索引数组，它的主要作用是 用于访问 nums 数组的元素
idx = np.arange(10)

print(idx)

print(nums[idx])

idx_rand = idx.copy()
np.random.shuffle(idx_rand)

nums[idx_rand]



[0 1 2 3 4 5 6 7 8 9]
[ 100  200  300  400  500  600  700  800  900 1000]


array([ 100,  200,  800,  300,  700,  900, 1000,  500,  400,  600])

In [7]:
mat = np.arange(1,13).reshape(3,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
mat[:,0]
#mat[:, 0] 用于选取 NumPy 矩阵的第一列（所有行，第 0 列）

array([1, 5, 9])

In [ ]:
mat[0,:]

array([1, 2, 3, 4])

In [ ]:
mat[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
mat[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
mat[-1,-2]
#mat[-1, -2] 用于访问 NumPy 矩阵中 "倒数第 1 行、倒数第 2 列" 的元素。

11

In [ ]:
# Mask

In [ ]:
mask = mat[:,3] >7

In [ ]:
mat[mask]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
mask

array([False,  True,  True])