<a href="https://colab.research.google.com/github/Ekiiio/week5/blob/main/Numpy_Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.arange(1,4)

In [3]:
a

array([1, 2, 3])

In [4]:
b = 1

In [5]:
a + b
#NumPy 的广播机制（Broadcasting），使得标量 b = 1 自动扩展为与 a 相同的形状，然后进行逐元素加法运算。

array([2, 3, 4])

In [6]:
c = np.arange(2,5)

In [7]:
(a,c)

(array([1, 2, 3]), array([2, 3, 4]))

In [8]:
a+c+1

array([4, 6, 8])